/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerTdc;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author unifgalbuquerque
 */
public class TipoContaFrame extends javax.swing.JFrame {

    /**
     * Creates new form TipoContaFrame
     */
    public TipoContaFrame() {
        initComponents();
        controller = new ControllerTdc(this);
    }

    public JToggleButton getBtcorrente() {
        return btcorrente;
    }

    public void setBtcorrente(JToggleButton btcorrente) {
        this.btcorrente = btcorrente;
    }

    public JToggleButton getBtpoupanca() {
        return btpoupanca;
    }

    public void setBtpoupanca(JToggleButton btpoupanca) {
        this.btpoupanca = btpoupanca;
    }

    public JToggleButton getBtsalario() {
        return btsalario;
    }

    public void setBtsalario(JToggleButton btsalario) {
        this.btsalario = btsalario;
    }

    public JLabel getLbctc() {
        return lbctc;
    }

    public void setLbctc(JLabel lbctc) {
        this.lbctc = lbctc;
    }

    public JLabel getLbescolha() {
        return lbescolha;
    }

    public void setLbescolha(JLabel lbescolha) {
        this.lbescolha = lbescolha;
    }

    public JTextField getTxtcpf() {
        return txtcpf;
    }

    public void setTxtcpf(JTextField txtcpf) {
        this.txtcpf = txtcpf;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbctc = new javax.swing.JLabel();
        txtcpf = new javax.swing.JTextField();
        lbescolha = new javax.swing.JLabel();
        btcorrente = new javax.swing.JToggleButton();
        btpoupanca = new javax.swing.JToggleButton();
        btsalario = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbctc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbctc.setText("Criar Tipo de Conta");

        txtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfActionPerformed(evt);
            }
        });

        lbescolha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbescolha.setText("Digite o CPF e escolha o tipo de conta");

        btcorrente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btcorrente.setText("Corrente");
        btcorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcorrenteActionPerformed(evt);
            }
        });

        btpoupanca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btpoupanca.setText("Poupança");
        btpoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpoupancaActionPerformed(evt);
            }
        });

        btsalario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btsalario.setText("Salário");
        btsalario.setToolTipText("");
        btsalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtcpf)
                            .addComponent(lbctc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btcorrente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btpoupanca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btsalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbescolha)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbctc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbescolha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btcorrente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btpoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalarioActionPerformed
        // TODO add your handling code here:
        controller.escolherConta();
        new ContaCadastradaFrame().setVisible(true);
    }//GEN-LAST:event_btsalarioActionPerformed

    private void btcorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcorrenteActionPerformed
        // TODO add your handling code here:
        controller.escolherConta();
        new ContaCadastradaFrame().setVisible(true);
    }//GEN-LAST:event_btcorrenteActionPerformed

    private void btpoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpoupancaActionPerformed
        // TODO add your handling code here:
        controller.escolherConta();
        new ContaCadastradaFrame().setVisible(true);
    }//GEN-LAST:event_btpoupancaActionPerformed

    private void txtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TipoContaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TipoContaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TipoContaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TipoContaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TipoContaFrame().setVisible(true);
//            }
//        });
//    }
    private ControllerTdc controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btcorrente;
    private javax.swing.JToggleButton btpoupanca;
    private javax.swing.JToggleButton btsalario;
    private javax.swing.JLabel lbctc;
    private javax.swing.JLabel lbescolha;
    private javax.swing.JTextField txtcpf;
    // End of variables declaration//GEN-END:variables
}
